version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:8.2-fpm-alpine
        volumes:
            - ./:/code
        networks:
            - code-network

networks:
    code-network:
        driver: bridge